version: "3.8"

services:
  mysql:
    image: mysql:8.0.34
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=almatur
    ports:
      - "3306:3306"
    volumes:
      - almatur-mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mysql

  backend:
    build: ./backend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  nginx:
    image: nginx:1.24.0-alpine
    restart: always
    volumes:
      - ./nginx/conf/almatur.conf:/etc/nginx/nginx.conf
      - ./frontend:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  almatur-mysql-data:
